#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    empid:
      type: integer
      required: true
      example: 100
    empname:
      type: string
      required: true
      example: "kittu"
    empstatus:
      type: string
      required: true
      example: "Active"
    emprole:
      type: string
      required: true
      example: "Developer"
    empsal:
      type: integer
      required: true
      example: 60000